language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-stable

env:
  global:
    - PILLAR_RELEASE=v8.0.2
    - PATH="$HOME/texlive/bin/x86_64-linux:$HOME/pillar/build:$PATH"

install:
  - git clone --branch "$PILLAR_RELEASE" https://github.com/pillar-markup/pillar.git "$HOME/pillar"
  - ( cd $HOME/pillar; ./scripts/build.sh; )
  - $HOME/pillar/scripts/ci/install-texlive
  - ./_support/latex/ensure-deps.sh

script:
  - pillar build pdf

after_failure:
  - cat _result/pdf/index.log

after_success:
  - mv _result/pdf/index.pdf PBE8-serbian-wip.pdf
  - curl --silent --location https://github.com/probonopd/uploadtool/raw/master/upload.sh | bash -s PBE8-serbian-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
 
